### ISSUE TITLE
enhancement request

### ISSUE THREAD

**Issue by brianhenson** [MicroPyramid/docker-box#12]
found your script via google and a couple of enhancement requests

Setup script:

- [ ] during the setting up of IP's explain further what each one is going to be used for. Example is containers vs bridge etc.

- [ ] have setup detect if files already exist and give option to remove them or continue install

Web interface:

- [ ] pull in existing docker containers from host

- [ ] give example format for mac address 

- [ ] error checking in web interface for inserting incorrect ip. (its logged to the console but not displayed)

**Comment by druuu** [comment]
1. Wiki pages will be created to explain about network stuff. While installing, links related to these wiki pages will be displayed.
2. Detecting files and removing them should be part of uninstall script, uninstall script will further try to cleanup installation traces.
3. Dockerbox can only manage containers which are created by it, because these containers will have init system and custom network.
4. A place holder will be provided for mac address format.
6. Error checking will be implemented.

**Comment by druuu** [comment]
@brianhenson do you have any suggestions or other enhancements?
